"""Publish realtime-serving certificates into a comparison latency table.

Shared orchestration behind ``scripts/publish_jetson_latency.py`` and the
``tether publish-latency`` CLI command — load certificates, render the table
(via :mod:`tether.realtime_cert`), write the results doc, and inject the table
into the README. Pure stdlib + ``tether.realtime_cert``; no GPU/torch needed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from tether.realtime_cert import (
    format_realtime_certificate_markdown,
    format_realtime_certificates_markdown_table,
)

README_TABLE_BEGIN = "<!-- BEGIN:jetson-latency-table -->"
README_TABLE_END = "<!-- END:jetson-latency-table -->"
DEFAULT_RESULTS_DOC = Path("reflex_context/06_experiments/jetson_latency_results.md")
CERT_FILENAME = "realtime-serving-cert.json"
CERT_KIND = "tether.realtime_serving_certificate"


class CertificateLoadError(ValueError):
    """Raised when a path is not a readable realtime serving certificate."""


def load_certificate(path: str | Path) -> tuple[Path, dict[str, Any]]:
    """Load one certificate from a JSON file or a directory containing it."""

    resolved = Path(path).expanduser()
    if resolved.is_dir():
        resolved = resolved / CERT_FILENAME
    if not resolved.is_file():
        raise CertificateLoadError(f"no certificate at {str(path)!r} (looked for {resolved})")
    try:
        data = json.loads(resolved.read_text())
    except json.JSONDecodeError as exc:
        raise CertificateLoadError(f"{resolved}: invalid JSON ({exc})") from exc
    if data.get("kind") != CERT_KIND:
        raise CertificateLoadError(
            f"{resolved}: not a realtime serving certificate (kind={data.get('kind')!r})"
        )
    return resolved, data


def inject_table_into_readme(readme: str | Path, table: str) -> bool:
    """Replace content between the README markers. Returns False if absent."""

    readme = Path(readme)
    if not readme.is_file():
        return False
    text = readme.read_text()
    if README_TABLE_BEGIN not in text:
        return False
    pre, rest = text.split(README_TABLE_BEGIN, 1)
    if README_TABLE_END not in rest:
        return False  # END marker missing or precedes BEGIN (malformed) — skip
    _, post = rest.split(README_TABLE_END, 1)
    new = f"{pre}{README_TABLE_BEGIN}\n\n{table.rstrip()}\n\n{README_TABLE_END}{post}"
    if new != text:
        readme.write_text(new)
    return True


def build_results_doc(table: str, sources: list[tuple[Path, dict[str, Any]]]) -> str:
    """Render the standalone Jetson latency results document."""

    parts = [
        "# Jetson latency results",
        "",
        "Generated by `tether publish-latency` (scripts/publish_jetson_latency.py) "
        "from `tether bench realtime` certificates. Roundtrip = end-to-end `/act` "
        "p50/p95/p99/max (ms). Re-run to refresh.",
        "",
        table.rstrip(),
        "",
        "## Per-certificate detail",
        "",
    ]
    for path, report in sources:
        parts.append(f"### `{path}`")
        parts.append("")
        parts.append(format_realtime_certificate_markdown(report).rstrip())
        parts.append("")
    return "\n".join(parts) + "\n"


def publish(
    cert_paths: list[str | Path],
    *,
    out: str | Path = DEFAULT_RESULTS_DOC,
    readme: str | Path | None = "README.md",
    title: str = "Realtime serving latency",
) -> dict[str, Any]:
    """Load certs, render the table, write the results doc, inject the README.

    Returns a summary dict ``{table, out, count, readme_updated}``. Raises
    :class:`CertificateLoadError` if any path is not a valid certificate. Pass
    ``readme=None`` to skip README injection.
    """

    sources = [load_certificate(path) for path in cert_paths]
    reports = [report for _, report in sources]
    table = format_realtime_certificates_markdown_table(reports, title=title)

    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_results_doc(table, sources))

    readme_updated = False
    if readme is not None:
        readme_updated = inject_table_into_readme(readme, table)

    return {
        "table": table,
        "out": str(out_path),
        "count": len(sources),
        "readme_updated": readme_updated,
    }
